<Project>
  <PropertyGroup>
    <ThoughtbenchTargetFramework>net10.0</ThoughtbenchTargetFramework>
    <ThoughtbenchWindowsTargetFramework>net10.0-windows</ThoughtbenchWindowsTargetFramework>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
  </PropertyGroup>
</Project>
