<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>$(ThoughtbenchWindowsTargetFramework)</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>..\..\assets\app-icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Thoughtbench.Core\Thoughtbench.Core.csproj" />
    <ProjectReference Include="..\Thoughtbench.Onnx\Thoughtbench.Onnx.csproj" />
  </ItemGroup>

</Project>
